apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: custom-exporter
  labels:
    app: custom-exporter
    release: prometheus
spec:
  selector:
    matchLabels:
      app: custom-exporter
  endpoints:
    - interval: 10s
      port: web
